version: '3.3'
services:
  db-vendas:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  api-informacoes:
    build: .
    image: api-informacoes-vendas:latest
    restart: always
    environment:
      MYSQL_HOST: db-vendas
      SPRING_PROFILES_ACTIVE: 'docker'
    ports:
      - '8081:8081'
    expose:
      - '8081'
    depends_on:
      - db-vendas

volumes:
  my-db:
